export const DEV_ICONS_MAP = {
  JavaScript: 'javascript-plain',
  TypeScript: 'typescript-plain',
  Python: 'python-plain',
  CSS: 'css3-plain',
  HTML: 'html5-plain',
  React: 'react-original',
  'Node.js': 'nodejs-plain',
  Express: 'express-original',
  MongoDB: 'mongodb-plain',
  PostgreSQL: 'postgresql-plain',
  Vue: 'vuejs-plain',
  'Next.js': 'nextjs-plain',
  'Nuxt.js': 'nuxtjs-plain',
  'Tailwind CSS': 'tailwindcss-plain',
  Svelte: 'svelte-plain',
  SvelteKit: 'sveltekit-plain',
  Vite: 'vite-plain',
  HCL: 'terraform-plain',
  AWS: 'aws-plain',
  Docker: 'docker-plain',
  Kubernetes: 'kubernetes-plain',
  Git: 'git-plain',
  GitHub: 'github-plain',
  GitLab: 'gitlab-plain',
  Astro: 'astro-plain',
  'React Native': 'react-original',
  Flutter: 'flutter-plain',
  Swift: 'swift-plain',
  Kotlin: 'kotlin-plain',
  Ruby: 'ruby-plain',
  Dockerfile: 'docker-plain',
  Shell: 'bash-plain',
  SCSS: 'sass-plain',
  Sass: 'sass-plain',
  PHP: 'php-plain',
  Wordpress: 'wordpress-plain',
  Handlebars: 'handlebars-plain',
  Java: 'java-plain',
  'Jupyter Notebook': 'jupyter-plain',
  Solidity: 'solidity-plain'
};

export const LANGUAGES_TO_HIDE = [
  'Objective-C',
  'Blade',
  'PLpgSQL',
  'PLSQL',
  'XSLT',
  'EJS',
  'Procfile',
  'Starlark',
  'Hack',
  'Twig'
];
